name: TNT

on:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '53 11 * * *'
    - cron: '0 15 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   TZ: Asia/Shanghai
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master


      - name: Add Go bin to PATH and Process Domains11
        run: |
          echo "$GOPATH/bin" >> $GITHUB_PATH
          
          FULL_TIME=$(date +"%Y-%m-%d %H:%M:%S")
          echo "完整时间: $FULL_TIME"
          

        shell: bash

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.4
          cache: true  # 自动缓存Go模块依赖
          cache-dependency-path: go.bin  # 根据go.sum变化更新缓存
          
      - name: Setup Dependencies
        run: sudo apt update && sudo apt-get install -y libpcap-dev gcc make git masscan

      - name: Cache ProjectDiscovery tools
        uses: actions/cache@v3
        id: tool-cache
        with:
          path: /home/runner/go/bin
          key: ${{ runner.os }}-pd-tools-V1

      - name: Setting up ProjectDiscovery tools
        if: steps.tool-cache.outputs.cache-hit != 'true'  # 仅在缓存未命中时安装
        env:
          GO111MODULE: on
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install -v github.com/lc/gau/v2/cmd/gau@latest
          go install -v github.com/tomnomnom/waybackurls@latest
          go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          go install -v github.com/projectdiscovery/mapcidr/cmd/mapcidr@latest
          go install -v github.com/zan8in/afrog/v3/cmd/afrog@latest
          
        shell: bash


      # - name: Add Go bin to PATH  # 确保工具可被后续步骤访问
      - name: Add Go bin to PATH and Process Domains
        run: |
          echo "$GOPATH/bin" >> $GITHUB_PATH
          rm -rf *_*.txt
          # 获取当前小时
          HOUR=$(date +%H)
          
          # 判断时间段并读取对应行
          if [ "$HOUR" -ge 18 ] && [ "$HOUR" -lt 23 ]; then
              # 18:00-23:00: 读取 1-3 行
              sed -n '1,4p' domains.txt > domains_work.txt && cat domains_work.txt
          elif [ "$HOUR" -ge 23 ] || [ "$HOUR" -lt 04 ]; then
              # 23:00-04:00: 读取 6-10 行
              sed -n '5,8p' domains.txt > domains_work.txt && cat domains_work.txt
          elif [ "$HOUR" -ge 04 ] && [ "$HOUR" -lt 08 ]; then
              # 04:00-08:00: 读取 11-15 行
              sed -n '9,12p' domains.txt > domains_work.txt && cat domains_work.txt
          else
              # 其他时间默认处理（可选）
              echo "Current hour $HOUR is outside defined ranges, skipping or using default."
          fi
        


      - name: Running DNS enumeration...
        run: |
          

          # subfinder -dL domains.txt -config config/subfinder-config.yaml | dnsx -t 350 -o active_subdomains.txt
          subfinder -dL domains_work.txt -config config/subfinder-config.yaml -o active_subdomains.txt
          dnsx -l active_subdomains.txt -t 350 | tee -a active_subdomains.txt
          sort -u active_subdomains.txt
          cat active_subdomains.txt
        
        shell: bash


      - name: Running port scanning...
        continue-on-error: true
        run: |
           
           naabu -l active_subdomains.txt -tp 1000 -c 1000 -rate 20000 |  tee active_urls.txt
           
        shell: bash

      - name: Running way/gau for getting all urls...
        continue-on-error: true
        timeout-minutes: 340
        run: |
          
          # cat active_urls.txt | gau --subs --blacklist png,jpg,gif,css --o ga_urls.txt
          # cat active_urls.txt | waybackurls > way_urls.txt
          # if [ $(wc -l < ga_urls.txt) -le 20000 ] && [ $(wc -l < way_urls.txt) -le 20000 ]; then
          #   sort -u ga_urls.txt way_urls.txt -o all_urls.txt
          # fi
          
      - name: Running NucleiFuzing for vulnerability assessment
        continue-on-error: true
        timeout-minutes: 340
        run: |
          nuclei -up && nuclei -ut && afrog
          git clone https://github.com/projectdiscovery/fuzzing-templates.git
          
          nuclei -l active_subdomains.txt -nh -it /fuzzing-templates -rl 800 -o fuzz_out.txt
          nuclei -l active_subdomains.txt -nh -s medium, high, critical -rl 800 -o hig_out.txt

          nuclei -l active_urls.txt -nh -it /fuzzing-templates -rl 800 -o fuzz_out1.txt
          nuclei -l active_urls.txt -nh -s medium, high, critical -rl 800 -o hig_out1.txt

          afrog -T active_subdomains.txt -rl 900 | tee af_out.txt
          afrog -T active_urls.txt -S medium, high, critical -rl 900 | tee af_out1.txt
          
        shell: bash

      - name: Create local changes
        run: |
          git add *.txt
      - name: Commit results to Github
        continue-on-error: true
        run: |
          git config --local user.email "admin@inbug.org"
          git config --global user.name "fuck-team"
          git commit -m "Fuck Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
